# Build settings
plugins:
  - jekyll-t4j
  - jekyll-paginate
  - jekyll-seo-tag


# Basic Properties
title: crow02531's blog
author: crow02531
permalink: pretty
avatar: /assets/avatar.jpg
sidebar_image: /assets/screenshots/2020-02-28_17.46.02.png
paginate: 5
navigation:
  dates: /nav/dates/
  tags: /nav/tags/
  about: /nav/about/
  works: /nav/works/


# T4J
t4j:
  packages:
    - chemfig
    - mhchem